# Generated by Django 5.1.5 on 2025-02-07 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0002_alter_libro_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revista',
            name='volumen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
